### ISSUE TITLE
feature request: support for arrays

### ISSUE THREAD

**Issue by xoac** [LouisGariepy/cornucopia#27]
If we add such modifications:

1. `migrations/1648515066_second.sql`:
```sql
CREATE TABLE CustomTable (
    col1 custom_composite,
    col2 spongebob_character,
    col3 custom_composite[]
);

INSERT INTO CustomTable (col1, col2, col3)
    VALUES (ROW('incredible', 42, 'Patrick'), 'Bob', ARRAY[ROW('incredible', 42, 'Patrick')]::custom_composite[]);
```

2. `queries/module_2.sql`
```sql
--! return_custom_type_array()
SELECT
    col3
FROM
    CustomTable;
```

Then `cornucopia generate` returns:
unsupported type `_custom_composite`

1. Will be possible to add support for arrays?
2. It would be nice to support `RUST_LOG` flag or `--verbose` sometimes it's hard to find source of error.

**Comment by LouisGariepy** [comment]
Hi @xoac, thanks for opening this issue.

1) Indeed, cornucopia does not yet support array types (you can find supported types [here](https://github.com/LouisGariepy/cornucopia#supported-types), but you're probably already aware of that).
    That said, `tokio-postgres` does support one-dimensional arrays, and  `cornucopia` aims to be be at feature parity, so this is indeed something I'm interested in supporting. It should be relatively easy to add, so you can look forward to a PR in the next few days.

2) Since this is unrelated, I'll open a new issue. I've tried to make the different errors as descriptive as possible, but in some places they leave a lot to be desired. This is something I'm already working on under the hood, but I've opened a new issue #28  so you can track the progress.

**Comment by LouisGariepy** [comment]
@xoac I have implemented this feature on the PR branch https://github.com/LouisGariepy/cornucopia/pull/29. Code is unfinished, but it passes testing so I should be able to release this feature along with better error reporting in the next few days. Cheers.

**Comment by LouisGariepy** [comment]
@xoac This should now work on `main`. I'll make a new release with these fixes and more in the coming days.

**Comment by xoac** [comment]
@LouisGariepy Awesome thanks!

**Comment by LouisGariepy** [comment]
@xoac, letting you know this is now in the latest release. Cheers.
